name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Executar o Terraform'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      destroy:
        description: 'Executar o Terraform Destroy'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      plan_destroy:
        description: 'Planejar o Terraform Destroy'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Terraform
    runs-on: ubuntu-latest
    
    # IMPORTANTE: Adicione o caminho aqui se for o mesmo para todos os steps
    # defaults:
    #   run:
    #     working-directory: seu/diretorio/terraform
         
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::396067939467:role/githubinfrarole
          aws-region: us-east-1

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO

      - name: Terraform Validate
        run: terraform validate
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO
      
      - name: Terraform Apply
        if: github.event.inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan # <-- CORRIGIDO
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO

      - name: Terraform Destroy Plan
        if: github.event.inputs.plan_destroy == 'true'
        run: terraform plan -destroy -out=tfplan-destroy # <-- CORRIGIDO
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve # <-- CORRIGIDO
        #working-directory: seu/diretorio/terraform # <-- ADICIONADO